# ~/.tmux.conf

# prefix를 C-a로 쓰고 싶다면
# unbind C-b
# set -g prefix C-a
# bind C-a send-prefix
#

# 기본 UX
# set -g mouse on
# set -g history-limit 100000
# set -g base-index 1
# setw -g pane-base-index 1
# set -g renumber-windows on

# 창/패널 분할
# bind | split-window -h
# bind - split-window -v

# vim 스타일 copy-mode
setw -g mode-keys vi

# ESC 지연 줄이기
set -sg escape-time 0

# true color
set -g default-terminal "tmux-256color"
set -as terminal-overrides ",xterm-256color:RGB"

# OSC 52 / clipboard
set -g set-clipboard on
